menu:
- {name: 'research', url: '/research'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

research:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}

courses:
- {name: 'Latin American Politics', url: 'latam-politics'}

social:
- {icon: 'github', link: 'https://github.com/vhurtadol'}
- {icon: 'twitter', link: 'https://twitter.com/verohurtado_'}

contacts:
- {name: 'Verónica Hurtado Lozada', title: 'PhD candidate', department: 'Political Science', institution: 'The University of British Columbia', phone: '(734) 249-1214', email: 'vhurtado@student.ubc.ca', image: 'hurtado_img.png'}
